### ISSUE TITLE
[Feature] Ability to choose existing resource group 

### ISSUE THREAD

**Issue by mortenlerudjordet** [Microsoft/Phoenix#29]
Would like you to also consider adding the ability to both choose an existing resource group and the ability to enter the name of the resource group to create

**Comment by rotata** [comment]
Thanks for the feedback, just to confirm, we have the ability to select an existing Resource Group (created by our RP), as part of the VM creation process, were you looking for anything different than that?

**Comment by mortenlerudjordet** [comment]
I think I understand now the reasoning behind this design.
You only expose resource groups previously created through the WAP portal. 

I was thinking more in the line of being able to choose from all the existing resource groups in the target Azure subscription.

Though this probably is not inline with the isolation design principle.

**Comment by raldaba** [comment]
Good observations.

Another thing playing a part in this dilemma is that we've seen VM provisioning errors coming directly from Azure when selecting certain kinds resource groups (for instance, when there's a region mismatch.) As you saw, our solution for v1 was limiting the resource groups to those created through WAP and stored in the database.

It was one of those scenarios where if the user has more customization options, they might run into an increased number of provisioning issues due to their Azure config.

If there's a significant demand for more customization with the resource groups, we can definitely revisit this with the community's suggestions.
